# Generated by Django 4.2.7 on 2024-02-20 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0022_user_idnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeapp.foodmenu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeapp.user')),
            ],
        ),
    ]
