# Generated by Django 4.2.7 on 2024-02-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0023_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='quantity',
            field=models.IntegerField(default=10),
        ),
    ]
