# Generated by Django 4.2.7 on 2024-02-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0026_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart',
        ),
    ]
