# Generated by Django 4.2.7 on 2024-02-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0026_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='quantity',
            field=models.IntegerField(default=10),
        ),
    ]
