# Generated by Django 4.2.7 on 2024-02-20 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0027_foodmenu_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='bookid',
            new_name='booking',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='food',
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeapp.booking')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeapp.foodmenu')),
            ],
        ),
    ]
