# Generated by Django 4.2.7 on 2024-02-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0028_checkout_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateTimeField(),
        ),
    ]
