# Generated by Django 4.2.7 on 2024-02-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0029_alter_checkout_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
