# Generated by Django 4.1.13 on 2024-03-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0032_checkout_delivery_date_checkout_isdelivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='isDelivered',
            field=models.CharField(default='Not Delivered', max_length=20),
        ),
    ]
